# Stage 1: Install all dependencies
FROM node:20-slim AS deps
WORKDIR /app
COPY package*.json ./
RUN apt-get update && apt-get install -y openssl && npm install --legacy-peer-deps

# Stage 2: Build the application
FROM node:20-slim AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
# 빌드 시점에 필요한 환경 변수들을 ARG로 선언
ARG DATABASE_URL
ARG NEXT_PUBLIC_GOOGLE_MAPS_JS_KEY
ARG NEXT_PUBLIC_KAKAOMAP_JS_KEY
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_VAPID_KEY
ARG NEXTAUTH_URL
ARG GOOGLE_API_KEY
ARG KAKAO_REST_API_KEY
ARG GOOGLE_CLIENT_SECRET
ARG KAKAO_CLIENT_ID
ARG KAKAO_CLIENT_SECRET
ARG NEXTAUTH_SECRET
ARG FIREBASE_SERVICE_ACCOUNT_KEY_BASE64

# ARG로 받은 변수들을 ENV로 설정하여 빌드 프로세스에서 사용 가능하도록 함
ENV DATABASE_URL=$DATABASE_URL
ENV NEXT_PUBLIC_GOOGLE_MAPS_JS_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_JS_KEY
ENV NEXT_PUBLIC_KAKAOMAP_JS_KEY=$NEXT_PUBLIC_KAKAOMAP_JS_KEY
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_VAPID_KEY=$NEXT_PUBLIC_FIREBASE_VAPID_KEY
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV GOOGLE_API_KEY=$GOOGLE_API_KEY
ENV KAKAO_REST_API_KEY=$KAKAO_REST_API_KEY
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
ENV KAKAO_CLIENT_SECRET=$KAKAO_CLIENT_SECRET
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV FIREBASE_SERVICE_ACCOUNT_KEY_BASE64=$FIREBASE_SERVICE_ACCOUNT_KEY_BASE64

# Dynamically create the firebase-config.js for the service worker
RUN echo "const firebaseConfig = {\
  apiKey: \"${NEXT_PUBLIC_FIREBASE_API_KEY}\",\
  authDomain: \"${NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN}\",\
  projectId: \"${NEXT_PUBLIC_FIREBASE_PROJECT_ID}\",\
  storageBucket: \"${NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET}\",\
  messagingSenderId: \"${NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID}\",\
  appId: \"${NEXT_PUBLIC_FIREBASE_APP_ID}\"\
};" > ./public/firebase-config.js

# npm run build 스크립트에 이미 prisma generate가 포함되어 있음
RUN npm run build

# Stage 3: Production image
FROM node:20-slim AS runner
WORKDIR /app

ENV NODE_ENV production

# Re-declare ARGs to make them available in the runner stage
ARG DATABASE_URL
ARG NEXT_PUBLIC_GOOGLE_MAPS_JS_KEY
ARG NEXT_PUBLIC_KAKAOMAP_JS_KEY
ARG NEXT_PUBLIC_FIREBASE_API_KEY
ARG NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ARG NEXT_PUBLIC_FIREBASE_PROJECT_ID
ARG NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ARG NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG NEXT_PUBLIC_FIREBASE_APP_ID
ARG NEXT_PUBLIC_FIREBASE_VAPID_KEY
ARG NEXTAUTH_URL
ARG GOOGLE_API_KEY
ARG KAKAO_REST_API_KEY
ARG GOOGLE_CLIENT_SECRET
ARG KAKAO_CLIENT_ID
ARG KAKAO_CLIENT_SECRET
ARG NEXTAUTH_SECRET
ARG FIREBASE_SERVICE_ACCOUNT_KEY_BASE64

# Copy necessary files from the builder stage
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/public ./public
# Copy the full node_modules from builder to ensure Prisma client is included
COPY --from=builder /app/node_modules ./node_modules
# Prisma 디렉토리 복사 추가
COPY --from=builder /app/prisma ./prisma

# Copy ENV variables from builder stage
ENV DATABASE_URL=$DATABASE_URL
ENV NEXT_PUBLIC_GOOGLE_MAPS_JS_KEY=$NEXT_PUBLIC_GOOGLE_MAPS_JS_KEY
ENV NEXT_PUBLIC_KAKAOMAP_JS_KEY=$NEXT_PUBLIC_KAKAOMAP_JS_KEY
ENV NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY
ENV NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
ENV NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID
ENV NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
ENV NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID
ENV NEXT_PUBLIC_FIREBASE_VAPID_KEY=$NEXT_PUBLIC_FIREBASE_VAPID_KEY
ENV NEXTAUTH_URL=$NEXTAUTH_URL
ENV GOOGLE_API_KEY=$GOOGLE_API_KEY
ENV KAKAO_REST_API_KEY=$KAKAO_REST_API_KEY
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET
ENV KAKAO_CLIENT_ID=$KAKAO_CLIENT_ID
ENV KAKAO_CLIENT_SECRET=$KAKAO_CLIENT_SECRET
ENV NEXTAUTH_SECRET=$NEXTAUTH_SECRET
ENV FIREBASE_SERVICE_ACCOUNT_KEY_BASE64=$FIREBASE_SERVICE_ACCOUNT_KEY_BASE64

CMD ["npm", "start"]